const $=id=>document.getElementById(id);let current=null,timer=null,lastVersion='',polling=false;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Request failed');return d}
const json=(method,data)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function error(e){$('uploadStatus').textContent=e.message;$('uploadStatus').className='error'}
async function init(){try{const s=await api('/api/session');$('loginPanel').hidden=s.authenticated;$('studio').hidden=!s.authenticated;if(s.authenticated)await projects()}catch(e){$('loginError').textContent=e.message}}
$('login').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',json('POST',{password:$('password').value}));$('password').value='';await init()}catch(x){$('loginError').textContent=x.message}};
async function projects(){const jobs=await api('/api/jobs');$('projects').innerHTML=jobs.length?jobs.map(j=>`<div class="project"><div><strong>${escape(j.settings.title)}</strong><small>${escape(j.status)} · ${new Date(j.created*1000).toLocaleString()}</small></div><div><button data-open="${j.id}" class="secondary">Open</button> <button data-delete="${j.id}" class="danger">Delete</button></div></div>`).join(''):'<p class="muted">Your uploaded projects will appear here.</p>'}
$('projects').onclick=async e=>{try{if(e.target.dataset.open)await openJob(e.target.dataset.open);if(e.target.dataset.delete&&confirm('Delete this project and all of its uploaded and rendered files?')){const id=e.target.dataset.delete;await api('/api/jobs/'+id,{method:'DELETE'});if(current===id){current=null;clearInterval(timer);$('job').hidden=true;$('idle').hidden=false}await projects()}}catch(x){error(x)}};
async function upload(id,kind,file,done,total){const size=4*1024*1024;for(let offset=0;offset<file.size;offset+=size){await api(`/api/jobs/${id}/upload/${kind}?offset=${offset}`,{method:'PUT',body:file.slice(offset,offset+size)});$('uploadStatus').textContent='Uploading '+Math.round((done+Math.min(offset+size,file.size))/total*100)+'% · '+file.name}}
$('create').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const images=Array.from(e.target.elements.images.files);if(images.length>12)return error(Error('Choose at most 12 images.'));const video=form.get('video'),voice=form.get('voice');if(video.size>2*1024**3||voice.size>100*1024**2)return error(Error('Video limit: 2 GB. Voiceover limit: 100 MB.'));const settings={title:form.get('title'),script:form.get('script'),quality:form.get('quality'),grade:form.get('grade'),images:images.length};for(const key of ['motion','masking','graphics','captions','sfx','transitions'])settings[key]=form.has(key);$('generate').disabled=true;$('uploadStatus').className='';try{const j=await api('/api/jobs',json('POST',settings));const files=[['video',video],['voice',voice],...images.map((f,i)=>['image-'+i,f])];const total=files.reduce((s,[k,f])=>s+f.size,0);let done=0;for(const [kind,file]of files){await upload(j.id,kind,file,done,total);done+=file.size}await api('/api/jobs/'+j.id+'/start',{method:'POST'});$('uploadStatus').textContent='Uploaded. The server is processing your video.';await openJob(j.id);await projects()}catch(x){error(x)}finally{$('generate').disabled=false}};
async function openJob(id){current=id;lastVersion='';clearInterval(timer);$('idle').hidden=true;$('job').hidden=false;$('finished').hidden=true;await poll();timer=setInterval(poll,4000)}
async function poll(){if(!current||polling)return;polling=true;try{const j=await api('/api/jobs/'+current);$('jobTitle').textContent=j.settings.title;$('jobState').textContent=j.status;$('jobMessage').textContent=j.message;$('progress').value=j.progress;$('log').href='/api/jobs/'+current+'/file/log';const running=['queued','processing','rendering'].includes(j.status);$('cancel').hidden=!running;const ready=['ready','review'].includes(j.status);$('finished').hidden=!ready;if(ready){const version=JSON.stringify(j.timeline);if(version!==lastVersion){lastVersion=version;show(j)}}if(!running&&j.status!=='uploading')clearInterval(timer)}catch(x){$('jobMessage').textContent=x.message}finally{polling=false}}
function show(j){const base='/api/jobs/'+j.id+'/file/';$('result').src=base+'output?v='+Date.now();$('download').href=base+'output';$('srt').href=base+'captions';$('timeline').href=base+'timeline';$('source').src=base+'source';$('shots').innerHTML=j.timeline.map((s,i)=>`<article class="shot" data-index="${i}"><header><span>SHOT ${i+1} · ${s.start.toFixed(1)}–${s.end.toFixed(1)}s</span><span>${s.approved?'Reviewed':'Needs review'}</span></header><textarea data-text rows="2">${escape(s.text)}</textarea><small>${escape(s.review_reason)}</small><label>Candidate<select data-candidate>${s.alternatives.map((a,k)=>`<option value="${k}" ${a.asset===s.asset&&Math.abs(a.source_time-s.source_time)<.01?'selected':''}>${a.asset==='video'?'Video at '+a.source_time.toFixed(1)+'s':'Image '+(Number(a.asset.split('-')[1])+1)} · similarity ${a.similarity.toFixed(2)}</option>`).join('')}<option value="custom">Custom timestamp</option></select></label><div class="controls"><label>Source start (seconds)<input data-start type="number" min="0" step="0.1" value="${s.source_time}"></label><button data-preview class="secondary">Preview source</button><button data-save class="secondary">Save shot</button></div><label class="approval"><input data-approved type="checkbox" ${s.approved?'checked':''}> I checked this scene and its context</label></article>`).join('');$('shots')._timeline=j.timeline}
$('shots').onchange=e=>{const card=e.target.closest('.shot');if(!card)return;const s=$('shots')._timeline[+card.dataset.index];if(e.target.matches('[data-candidate]')&&e.target.value!=='custom'){const a=s.alternatives[+e.target.value];card.querySelector('[data-start]').value=a.source_time;card.querySelector('[data-approved]').checked=false}};
$('shots').onclick=async e=>{const card=e.target.closest('.shot');if(!card)return;const index=+card.dataset.index,s=$('shots')._timeline[index],choice=card.querySelector('[data-candidate]').value;const asset=choice==='custom'?'video':s.alternatives[+choice].asset;const start=Number(card.querySelector('[data-start]').value);try{if(e.target.hasAttribute('data-preview')){if(asset!=='video')return error(Error('This candidate is a supplied image. Its asset name is shown in the candidate list.'));$('source').currentTime=start;await $('source').play();$('source').ontimeupdate=()=>{if($('source').currentTime>=start+s.end-s.start)$('source').pause()}}if(e.target.hasAttribute('data-save')){await api('/api/jobs/'+current+'/shot',json('PUT',{index,asset,source_time:start,text:card.querySelector('[data-text]').value,approved:card.querySelector('[data-approved]').checked}));e.target.textContent='Saved';$('jobMessage').textContent='Changes saved. Click Render saved changes to update the MP4.'}}catch(x){error(x)}};
$('rerender').onclick=async()=>{try{await api('/api/jobs/'+current+'/render',{method:'POST'});await openJob(current)}catch(x){error(x)}};
$('cancel').onclick=async()=>{try{await api('/api/jobs/'+current+'/cancel',{method:'POST'});await poll();await projects()}catch(x){error(x)}};
init();
